#pragma once

#define	PIXEL_UNIT	20	// 单位像素
#define	GAMEAREA_WIDTH	10	// 游戏区宽
#define	GAMEAREA_HEIGHT	22	// 游戏区高

#define PIXEL_GAMEAREA_WIDTH PIXEL_UNIT * GAMEAREA_WIDTH
#define PIXEL_GAMEAREA_HEIGHT PIXEL_UNIT * GAMEAREA_HEIGHT

#define ORIGIN_X 220
#define ORIGIN_Y 20
